### PR TITLE
Forms

### PR DESCRIPTION
**Pull request by k00cur1k**
issue #21

### CODE REVIEW

**Review by mousetom-sk — CHANGES_REQUESTED** [review]
I see some potential for improvement in the following directions:
- I would add an option to submit an AJAX-handled form by pressing ENTER while the last input is in focus.
- I also realized that we should label each input field for better accessibility and easier double-checking. By labeling I mean providing a standalone label instead of a placeholder. (I know, this is not your fault, I should have thought about that sooner.)
- Login form: Error messages for email should appear directly below the email field. Error messages for password are not displayed at all, but they should be.
- First user: The page should automatically reload after successfully creating a new user. What happens instead is that the modal disappears as if it was opened through the application menu.
- I would slightly change the error handling process:
	if (typeof response.responseJSON != 'undefined') {
		if (response.status === 422) {
			...
		} else if (typeof response.responseJSON.displayMessage != 'undefined') {
			...
		}
	}

	Toast.fire({
		icon: 'error',
		title: <general error message, i.e. 'Something went wrong, please, try again later.'>
	})

**Comment by k00cur1k** [comment]
I`m not fan of changing js error handling structure which is already done, because you want to only add new if statements with error codes. I think it`s not necessary, because I`m already handling all possible outputs.

**Comment by k00cur1k** [comment]
all fixed

**Review by mousetom-sk — APPROVED** [review]
Should be ok now.

**Pull request merged**
